### ISSUE TITLE
Type enforcement failing with typing.Type

### ISSUE THREAD

**Issue by h-tracey** [connor-makowski/type_enforced#2]
The Enforcer fails when dealing with typehinted inherited methods. 

```
from type_enforced import Enforcer
from typing import Type

class Foo():
    def __init__(self) -> None:
        pass

class Bar(Foo):
    def __init__(self) -> None:
        super().__init__()

@Enforcer
class Baz():
    def __init__(self, use_class: Type[Foo]) -> None:
        self.object = use_class()
```

fails with 
```
>>> fail = Baz(Foo())
>>> Exception: (Baz.__init__): Type mismatch for typed variable `use_class`. Expected one of the following `[typing.Type[__main__.Foo]]` but got `<class '__main__.Foo'>` instead.
```

**Comment by connor-makowski** [comment]
It is also worth noting that you must upgrade to 0.0.7 to get the new functionality for the uninitialized class instances.

Let me know if this solves your issue.

**Comment by h-tracey** [comment]
@connor-makowski Thanks for getting back to me! The inclusion of the un-instantiated classes is a very welcome addition, and thanks for the clarification in the docs. However, This doesn't solve the issue I'm getting with Typing classes. 

In the toy examples below, I'm using the Typing classes as [type aliases](https://docs.python.org/3.7/library/typing.html#type-aliases) for generics, and it appears that none of the fundamental type hints are currently supported, as a built-in type class is not a match to a typing type.
```
import type_enforced
import typing

@type_enforced.Enforcer
def optional_param(foo: typing.Optional[int] = None):
    pass

a = optional_param(foo=7) #fails
b = optional_param() #fails
```
```
import type_enforced
import typing

@type_enforced.Enforcer
def multi_type_param(foo: typing.Union[int, str]):
    pass

a = multi_type_param(1) #fails
b = multi_type_param('hello') #fails
```
```
import type_enforced
import typing

@type_enforced.Enforcer
def tuple_param(foo: typing.Tuple[int, int]):
    pass

a = tuple_param((1, 2)) #fails
```

**Comment by connor-makowski** [comment]
As of right now, this package does not attempt to exactly match or fully support the typing module. We only support typing of built in types or custom class types using our own custom nomenclature. The main README.md details the limited set of features available for enforcing typing on the fly using this package. 

To address some of your examples:

We have no optional typing. If a function/method has a type or list of types specified, it is enforced.

To allow for multiple types as inputs, you can use our special bracket list based nomenclature in the type hints:

```py
@type_enforced.Enforcer
def multi_type_param(foo: [int, str]):
    pass
```

The package does not currently enforce sub items inside of a passed object. You would need to add special code to do that for you:

```py
@type_enforced.Enforcer
def tuple_param(foo: tuple):
    for i in foo:
        assert type(i)==int
```

With all that said, this is a great feature request to consider moving forward. Since we will not be directly addressing this ticket soon, I am going to go ahead and close this issue for now.
